"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., dashboard-layout.v1.tsx).
 * To stop versioning this component, run: npx uifork promote dashboard-layout <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./dashboard-layout.versions"

export function DashboardLayout(props: any) {
  return (
    <ForkedComponent
      id="dashboard-layout"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }