/**
 * THIS FILE IS GENERATED by uifork.
 * @uifork-export Sidebar
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote sidebar <version-id>
 */
import { Sidebar as SidebarV1 } from "./sidebar.v1"
import { Sidebar as SidebarV2 } from "./sidebar.v2"
import { Sidebar as SidebarV3 } from "./sidebar.v3"
import { Sidebar as SidebarV4 } from "./sidebar.v4"
import { Sidebar as SidebarV5 } from "./sidebar.v5"
export const VERSIONS = {
  "v1": {
    render: SidebarV1,
    label: "Default (Light/Dark)",
    description: "Original sidebar with adaptive theme",
  },
  "v2": {
    render: SidebarV2,
    label: "Dark Edition",
    description: "Always dark theme with purple accent",
  },
  "v3": {
    render: SidebarV3,
    label: "Paper Design",
    description: "Based on Paper Design specs with refined spacing",
  },
  "v4": {
    render: SidebarV4,
    label: "Paper Design Light",
    description: "Exact Paper Design values: white bg, precise colors",
  },
  "v5": {
    render: SidebarV5,
    label: "Classic Elegant",
    description: "Garamond font, red/green/gold palette, serif typography",
  },
}
