"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., sidebar.v1.tsx).
 * To stop versioning this component, run: npx uifork promote sidebar <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./sidebar.versions"

export function Sidebar(props: any) {
  return (
    <ForkedComponent
      id="sidebar"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
